name = "JQuants"
uuid = "9ec6771f-e08b-47bc-92e5-dcad4d5f32bd"
authors = ["ki-chi <k.brilliant@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
DataFrames = "1"
HTTP = "1"
JSON = "0.21"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
